name = "PRONTO"
uuid = "97df7862-8962-462b-83f4-d1fea1a8c26c"
authors = ["mantas <mantas@case.edu>", "jay"]
version = "0.3.0-dev"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
SciMLBase = "1.38.3"
Symbolics = "4.6.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "BenchmarkTools"]
